from datetime import timedelta
import logging
import secrets

from odoo import api, fields, models
from odoo.addons.iot_base.tools.payload_signature import hmac_sign

_logger = logging.getLogger(__name__)


class IotBox(models.Model):
    _name = 'iot.box'
    _description = 'IoT Box'

    name = fields.Char('Name', readonly=True)
    identifier = fields.Char(string='Identifier', readonly=True)
    device_ids = fields.One2many('iot.device', 'iot_id', string="Devices")
    device_count = fields.Integer(compute='_compute_device_count')
    ip = fields.Char('Domain Address', readonly=True)
    ip_url = fields.Char('IoT Box Home Page', readonly=True, compute='_compute_ip_url')
    drivers_auto_update = fields.Boolean('Automatic drivers update', help='Automatically update drivers when the IoT Box boots', default=True)
    version = fields.Char('Image Version', readonly=True)
    company_id = fields.Many2one('res.company', 'Company')
    ssl_certificate_end_date = fields.Datetime('SSL Certificate End Date', readonly=True)

    def _default_token(self):
        """Generate a token used in the iot box "token" field or by the wizards used to connect a new IoT Box.
        Also clears the token from the configuration parameters if used to assign the "token" field to
        make the token unique per IoT Box.

        :return: The token generated by the wizard.
        """
        icp_sudo = self.env['ir.config_parameter'].sudo()

        iot_token_param = icp_sudo.search([('key', '=', 'iot.iot_token')], limit=1)
        iot_token_value = iot_token_param.value if iot_token_param else None
        if (
            not iot_token_param
            or not iot_token_value
            or iot_token_param.write_date + timedelta(minutes=15) < fields.Datetime.now()
        ):
            _logger.info("No valid token found in the configuration parameters, generating a new one.")
            iot_token_value = secrets.token_hex(16)
            icp_sudo.set_param('iot.iot_token', iot_token_value)
        return iot_token_value

    token = fields.Char(default=lambda self: self._default_token(), readonly=True)

    @api.model
    def sign_communication(self, iot_box_ip, url, payload):
        """Compute HMAC signature for the url and the payload of a request with
        the IoT Box `token` as key.

        In order not to multiply orm requests, we also check the SSL certificate validity
        in the same method.

        :param iot_box_ip: ip of the ioT box
        :param url: url of the request
        :param payload: payload of the request
        :return: HMAC signature of the timestamp, url and payload, and a boolean
            indicating if the SSL certificate is valid
        :rtype: dict
        """
        iot_id = self.env['iot.box'].search([('ip', '=', iot_box_ip)], limit=1)

        return {
            "signature": hmac_sign(url, payload, iot_id.token),
            "isSslCertificateValid": (
                iot_id.ssl_certificate_end_date and iot_id.ssl_certificate_end_date > fields.Datetime.now()
            ),
        }

    def _compute_ip_url(self):
        for box in self:
            if not box.ip:
                box.ip_url = False
            else:
                url = 'https://%s' if box.get_base_url()[:5] == 'https' else 'http://%s:8069'
                box.ip_url = url % box.ip

    def _compute_device_count(self):
        for box in self:
            box.device_count = len(box.device_ids)

    @api.ondelete(at_uninstall=True)
    def _unlink_iot_box(self):
        self.env['iot.channel']._send_message({
            "iot_identifiers": self.mapped('identifier')
        }, 'server_clear')

    def open_homepage(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_url',
            'url': self.ip_url,
            'target': 'new',
        }

    @api.model
    def connect_iot_box(self, local_iot_boxes):
        """
        This method is called when pressing the "Connect" button in the IoT app.
        Used to connect a new IoT Box to a database.
        :return: action to open the wizard view depending on the result of the iot-proxy request sent by the wizard
        """
        wizard = self.env['add.iot.box'].create({})
        self.env['iot.discovered.box'].create([
            {
                "pairing_code": box["pairing_code"],
                "serial_number": box.get("serial_number"),
                "add_iot_box_wizard_id": wizard.id,
            }
            for box in local_iot_boxes
        ])
        return wizard.add_iot_box_wizard_action()
