from datetime import timedelta
import hashlib
import hmac
import json
import logging
import secrets
import time

from odoo import fields, models
from urllib.parse import urlparse, parse_qsl

_logger = logging.getLogger(__name__)


class IotBox(models.Model):
    _name = 'iot.box'
    _description = 'IoT Box'

    name = fields.Char('Name', readonly=True)
    identifier = fields.Char(string='Identifier (Mac Address)', readonly=True)
    device_ids = fields.One2many('iot.device', 'iot_id', string="Devices")
    device_count = fields.Integer(compute='_compute_device_count')
    ip = fields.Char('Domain Address', readonly=True)
    ip_url = fields.Char('IoT Box Home Page', readonly=True, compute='_compute_ip_url')
    drivers_auto_update = fields.Boolean('Automatic drivers update', help='Automatically update drivers when the IoT Box boots', default=True)
    version = fields.Char('Image Version', readonly=True)
    is_websocket_active = fields.Boolean("Is Websocket active?", readonly=True, default=False)
    company_id = fields.Many2one('res.company', 'Company')

    def _default_token(self):
        """Retrieve the token generated by "add.iot.box" wizard.
        Also clears the token from the configuration parameters to avoid
        reusing it for another IoT Box.

        :return: The token generated by the wizard.
        """
        iot_token_param = self.env['ir.config_parameter'].sudo().search([('key', '=', 'iot_token')], limit=1)
        if (
            not iot_token_param
            or not iot_token_param.value
            or iot_token_param.write_date + timedelta(minutes=15) < fields.Datetime.now()
        ):
            _logger.info("No token found in the configuration parameters, generating one.")
            return secrets.token_hex(16)

        token = iot_token_param.value
        iot_token_param.write({'value': ''})  # Clear the token to force creating a new one for next IoT Box
        return token

    token = fields.Char(default=lambda self: self._default_token(), readonly=True)

    def hmac_sign(self, url, payload, t=None):
        """Compute HMAC signature for the url and the payload of a request with
        the IoT Box `token` as key.

        :param url: url of the request
        :param payload: payload of the request
        :param float t: timestamp to use for the signature, if not provided, the current
            time is used
        :return: HMAC signature of the timestamp, url and payload
        """
        if not t:
            t = time.time()

        parsed_url = urlparse(url)
        query_params = dict(parse_qsl(parsed_url.query, keep_blank_values=True))

        payload = "%s|%s|%s|%s" % (
            int(t),
            parsed_url.path,
            json.dumps(query_params, sort_keys=True),
            json.dumps(payload, sort_keys=True),
        )
        return hmac.new(self.token.encode(), payload.encode(), hashlib.sha256).hexdigest()


    def _compute_ip_url(self):
        for box in self:
            if not box.ip:
                box.ip_url = False
            else:
                url = 'https://%s' if box.get_base_url()[:5] == 'https' else 'http://%s:8069'
                box.ip_url = url % box.ip

    def _compute_device_count(self):
        for box in self:
            box.device_count = len(box.device_ids)
